services:
  server-production:
    container_name: poker-server
    image: poker-server:latest
    build:
      context: server
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    profiles:
      - production

# ClusterIP networks are internal to the cluster by default
