services:
  server-development:
    container_name: poker-server
    build:
      context: server
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    volumes:
      - ./server/backend:/app/backend
      - ./server/frontend:/app/frontend
    networks:
      - internal
    profiles:
      - development

  reverse-proxy-development:
    container_name: poker-reverse-proxy
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - server-development
    restart: unless-stopped
    networks:
      - internal
      - external
    ports:
      - "80:80"
    profiles:
      - development

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
