services:
  server-production:
    container_name: counter-server
    build:
      context: server
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    profiles:
      - production

# ClusterIP networks are internal to the cluster by default
