services:
  server-production:
    container_name: counter-server
    build:
      context: server
      dockerfile: Dockerfile
      target: production
      args:
        RUST_TARGET: ${RUST_TARGET:?need to know cpu architecture for server musl build}
    restart: unless-stopped
    profiles:
      - production

# ClusterIP networks are internal to the cluster by default
