services:
  server:
    build:
      context: counter
      dockerfile: Dockerfile
      target: production
      args:
        RUST_TARGET: ${RUST_TARGET}
    networks:
      - internal
    environment:
      - RUST_LOG=1
      - RUST_BACKTRACE=1

  reverse-proxy:
    image: nginx:alpine
    depends_on:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # readonly mount our proxy
    ports:
      - "3670:80" # bind host 3670 to our nginx http redirect
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge