---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-cloudflared
  template:
    metadata:
      labels:
        app: counter-cloudflared
    spec:
      containers:
        - name: counter-cloudflared
          image: counter-cloudflared-production:latest
          imagePullPolicy: Never
          args: [tunnel, --no-autoupdate, run]
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: counter-secrets
                  key: TUNNEL_TOKEN

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-reverse-proxy
  template:
    metadata:
      labels:
        app: counter-reverse-proxy
    spec:
      containers:
        - name: counter-reverse-proxy
          image: counter-reverse-proxy-production:latest
          imagePullPolicy: Never

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-server
  template:
    metadata:
      labels:
        app: counter-server
    spec:
      containers:
        - name: counter-server
          image: counter-server-production:latest
          imagePullPolicy: Never
          env:
            - name: UI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-secrets
                  key: UI_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: counter-server
spec:
  selector:
    app: counter-server
  ports:
    - port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: counter-reverse-proxy
spec:
  selector:
    app: counter-reverse-proxy
  ports:
    - port: 80
