---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-cloudflared
  labels:
    io.kompose.service: counter-cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: counter-cloudflared
  template:
    metadata:
      labels:
        io.kompose.service: counter-cloudflared
    spec:
      containers:
        - name: counter-cloudflared
          image: counter-cloudflared-production:latest
          imagePullPolicy: Never
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: counter-secrets
                  key: TUNNEL_TOKEN
                  optional: false
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-reverse-proxy
  labels:
    io.kompose.service: counter-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: counter-reverse-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: counter-reverse-proxy
    spec:
      containers:
        - name: counter-reverse-proxy
          image: counter-reverse-proxy-production:latest
          imagePullPolicy: Never
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-server
  labels:
    io.kompose.service: counter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: counter-server
  template:
    metadata:
      labels:
        io.kompose.service: counter-server
    spec:
      containers:
        - name: counter-server
          image: counter-server-production:latest
          imagePullPolicy: Never
          env:
            - name: UI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-secrets
                  key: UI_PASSWORD
                  optional: false
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: counter-server
spec:
  type: ClusterIP
  selector:
    io.kompose.service: counter-server
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: counter-reverse-proxy
spec:
  type: ClusterIP
  selector:
    io.kompose.service: counter-reverse-proxy
  ports:
    - port: 80
      targetPort: 80
